export const LAYOUT_STORAGE_KEY = 'porest-dashboard-layouts';
export const WIDGETS_STORAGE_KEY = 'porest-dashboard-widgets';

export const WIDGETS = [
  { id: 'profile', label: '내 정보', defaultH: 14, defaultW: 3 },
  { id: 'vacation-stats', label: '휴가 현황', defaultH: 5, defaultW: 6 },
  { id: 'month-stats', label: '월별 휴가 통계', defaultH: 9, defaultW: 6 },
  { id: 'type-stats', label: '휴가 유형별 통계', defaultH: 14, defaultW: 3 },
  { id: 'schedule', label: '근무 일정', defaultH: 9, defaultW: 5 },
  { id: 'vacation-application', label: '휴가 신청 내역', defaultH: 8, defaultW: 12 },
  { id: 'vacation-request-stats', label: '휴가 신청 통계', defaultH: 6, defaultW: 12 },
  { id: 'vacation-history', label: '휴가 내역', defaultH: 11, defaultW: 6 },
  { id: 'dues', label: '회비 내역', defaultH: 11, defaultW: 6 },
  { id: 'total-dues', label: '회비 현황', defaultH: 5, defaultW: 6 },
  { id: 'user-birth-dues', label: '월별 생일비 입금 현황', defaultH: 9, defaultW: 7 },
  { id: 'user-company-stats', label: '회사별 인원 현황', defaultH: 5, defaultW: 6 },
  { id: 'system-check', label: '시스템 데일리 체크', defaultH: 8, defaultW: 6 },
];

export const defaultLayouts = {
  lg: [
    { i: 'profile', x: 0, y: 0, w: 3, h: 14 },
    { i: 'vacation-stats', x: 3, y: 0, w: 6, h: 5 },
    { i: 'month-stats', x: 3, y: 5, w: 6, h: 9 },
    { i: 'type-stats', x: 9, y: 0, w: 3, h: 14 },
    { i: 'schedule', x: 0, y: 19, w: 5, h: 9 },
    { i: 'vacation-application', x: 0, y: 34, w: 12, h: 8 },
    { i: 'vacation-request-stats', x: 0, y: 28, w: 12, h: 6 },
    { i: 'vacation-history', x: 0, y: 42, w: 6, h: 11 },
    { i: 'dues', x: 6, y: 42, w: 6, h: 11 },
    { i: 'total-dues', x: 0, y: 14, w: 6, h: 5 },
    { i: 'user-birth-dues', x: 5, y: 19, w: 7, h: 9 },
    { i: 'user-company-stats', x: 6, y: 14, w: 6, h: 5 },
    { i: 'system-check', x: 0, y: 19, w: 6, h: 8 },
  ],
  md: [
    { i: 'profile', x: 0, y: 0, w: 5, h: 14 },
    { i: 'vacation-stats', x: 5, y: 0, w: 5, h: 4 },
    { i: 'month-stats', x: 0, y: 14, w: 10, h: 8 },
    { i: 'type-stats', x: 5, y: 4, w: 5, h: 8 },
    { i: 'schedule', x: 0, y: 22, w: 10, h: 8 },
    { i: 'vacation-application', x: 0, y: 30, w: 10, h: 8 },
    { i: 'vacation-request-stats', x: 0, y: 38, w: 10, h: 4 },
    { i: 'vacation-history', x: 0, y: 42, w: 10, h: 14 },
    { i: 'dues', x: 0, y: 56, w: 10, h: 14 },
    { i: 'total-dues', x: 0, y: 70, w: 10, h: 4 },
    { i: 'user-birth-dues', x: 0, y: 74, w: 10, h: 14 },
    { i: 'user-company-stats', x: 0, y: 88, w: 10, h: 4 },
    { i: 'system-check', x: 0, y: 92, w: 10, h: 8 },
  ],
  sm: [
    { i: 'profile', x: 0, y: 0, w: 6, h: 14 },
    { i: 'vacation-stats', x: 0, y: 14, w: 6, h: 4 },
    { i: 'month-stats', x: 0, y: 18, w: 6, h: 8 },
    { i: 'type-stats', x: 0, y: 26, w: 6, h: 8 },
    { i: 'schedule', x: 0, y: 34, w: 6, h: 8 },
    { i: 'vacation-application', x: 0, y: 42, w: 6, h: 8 },
    { i: 'vacation-request-stats', x: 0, y: 50, w: 6, h: 4 },
    { i: 'vacation-history', x: 0, y: 54, w: 6, h: 14 },
    { i: 'dues', x: 0, y: 68, w: 6, h: 14 },
    { i: 'total-dues', x: 0, y: 82, w: 6, h: 4 },
    { i: 'user-birth-dues', x: 0, y: 86, w: 6, h: 14 },
    { i: 'user-company-stats', x: 0, y: 100, w: 6, h: 4 },
    { i: 'system-check', x: 0, y: 104, w: 6, h: 8 },
  ]
};
