export const LAYOUT_STORAGE_KEY = 'porest-dashboard-layouts';
export const WIDGETS_STORAGE_KEY = 'porest-dashboard-widgets';

export const WIDGETS = [
  { id: 'profile', label: '내 정보', defaultH: 14, defaultW: 3, minW: 3, maxW: 6, minH: 10, maxH: 13 },
  { id: 'vacation-stats', label: '휴가 현황', defaultH: 4, defaultW: 6, minW: 4, maxW: 12, minH: 4, maxH: 4 },
  { id: 'month-stats', label: '월별 휴가 통계', defaultH: 9, defaultW: 6, minW: 4, maxW: 12, minH: 6, maxH: 9 },
  { id: 'type-stats', label: '휴가 유형별 통계', defaultH: 14, defaultW: 3, minW: 3, maxW: 8, minH: 10, maxH: 20 },
  { id: 'schedule', label: '근무 일정', defaultH: 9, defaultW: 7, minW: 7, maxW: 12, minH: 6, maxH: 16 },
  { id: 'vacation-application', label: '휴가 신청 내역', defaultH: 8, defaultW: 12, minW: 6, maxW: 12, minH: 6, maxH: 20 },
  { id: 'vacation-request-stats', label: '휴가 신청 통계', defaultH: 6, defaultW: 12, minW: 6, maxW: 12, minH: 6, maxH: 12 },
  { id: 'vacation-history', label: '휴가 내역', defaultH: 11, defaultW: 6, minW: 4, maxW: 12, minH: 8, maxH: 20 },
  { id: 'dues', label: '회비 내역', defaultH: 11, defaultW: 6, minW: 4, maxW: 12, minH: 8, maxH: 20 },
  { id: 'total-dues', label: '회비 현황', defaultH: 5, defaultW: 6, minW: 5, maxW: 12, minH: 5, maxH: 10 },
  { id: 'user-birth-dues', label: '월별 생일비 입금 현황', defaultH: 9, defaultW: 7, minW: 7, maxW: 12, minH: 6, maxH: 16 },
  { id: 'user-company-stats', label: '회사별 인원 현황', defaultH: 5, defaultW: 6, minW: 5, maxW: 12, minH: 5, maxH: 12 },
  { id: 'system-check', label: '시스템 데일리 체크', defaultH: 8, defaultW: 6, minW: 3, maxW: 12, minH: 6, maxH: 16 },
  { id: 'today-work-status', label: '오늘 업무 현황', defaultH: 6, defaultW: 6, minW: 3, maxW: 12, minH: 4, maxH: 8 },
];

export const defaultLayouts = {
  lg: [
    { i: 'profile', x: 0, y: 0, w: 3, h: 13 },
    { i: 'today-work-status', x: 3, y: 0, w: 6, h: 6 },
    { i: 'vacation-stats', x: 3, y: 6, w: 6, h: 4 },
    { i: 'month-stats', x: 3, y: 10, w: 6, h: 9 },
    { i: 'type-stats', x: 9, y: 0, w: 3, h: 13 },
    { i: 'total-dues', x: 0, y: 13, w: 6, h: 5 },
    { i: 'user-company-stats', x: 6, y: 13, w: 6, h: 5 },
    { i: 'schedule', x: 0, y: 18, w: 7, h: 9 },
    { i: 'system-check', x: 7, y: 18, w: 5, h: 8 },
    { i: 'user-birth-dues', x: 0, y: 27, w: 7, h: 9 },
    { i: 'vacation-request-stats', x: 0, y: 36, w: 12, h: 6 },
    { i: 'vacation-application', x: 0, y: 42, w: 12, h: 8 },
    { i: 'vacation-history', x: 0, y: 50, w: 6, h: 11 },
    { i: 'dues', x: 6, y: 50, w: 6, h: 11 },
  ],
  md: [
    { i: 'profile', x: 0, y: 0, w: 5, h: 13 },
    { i: 'today-work-status', x: 5, y: 0, w: 5, h: 6 },
    { i: 'vacation-stats', x: 5, y: 6, w: 5, h: 4 },
    { i: 'type-stats', x: 5, y: 10, w: 5, h: 9 },
    { i: 'month-stats', x: 0, y: 13, w: 10, h: 9 },
    { i: 'schedule', x: 0, y: 22, w: 10, h: 9 },
    { i: 'vacation-application', x: 0, y: 31, w: 10, h: 8 },
    { i: 'vacation-request-stats', x: 0, y: 39, w: 10, h: 6 },
    { i: 'vacation-history', x: 0, y: 45, w: 10, h: 14 },
    { i: 'dues', x: 0, y: 59, w: 10, h: 14 },
    { i: 'total-dues', x: 0, y: 73, w: 10, h: 5 },
    { i: 'user-birth-dues', x: 0, y: 78, w: 10, h: 14 },
    { i: 'user-company-stats', x: 0, y: 92, w: 10, h: 5 },
    { i: 'system-check', x: 0, y: 97, w: 10, h: 8 },
  ],
  sm: [
    { i: 'profile', x: 0, y: 0, w: 6, h: 13 },
    { i: 'today-work-status', x: 0, y: 13, w: 6, h: 6 },
    { i: 'vacation-stats', x: 0, y: 19, w: 6, h: 4 },
    { i: 'month-stats', x: 0, y: 23, w: 6, h: 9 },
    { i: 'type-stats', x: 0, y: 32, w: 6, h: 13 },
    { i: 'schedule', x: 0, y: 45, w: 6, h: 9 },
    { i: 'vacation-application', x: 0, y: 54, w: 6, h: 8 },
    { i: 'vacation-request-stats', x: 0, y: 62, w: 6, h: 6 },
    { i: 'vacation-history', x: 0, y: 68, w: 6, h: 14 },
    { i: 'dues', x: 0, y: 82, w: 6, h: 14 },
    { i: 'total-dues', x: 0, y: 96, w: 6, h: 5 },
    { i: 'user-birth-dues', x: 0, y: 101, w: 6, h: 14 },
    { i: 'user-company-stats', x: 0, y: 115, w: 6, h: 5 },
    { i: 'system-check', x: 0, y: 120, w: 6, h: 8 },
  ],
};
