// Types
export type {
  VacationGrantMethod,
  VacationUnit,
  UsageUnit,
  SalaryType,
  Gender,
  DocumentSubmission,
  RecurringType,
  VacationPolicy,
  VacationConfig,
  PostUseVacationReq,
  PostUseVacationResp,
  GetUserVacationHistoryReq,
  VacationGrantInfo,
  VacationUsageInfo,
  GetUserVacationHistoryResp,
  GetAllUsersVacationHistoryResp,
  GetAvailableVacationsReq,
  AvailableVacationByType,
  GetAvailableVacationsResp,
  PutUpdateVacationUsageReq,
  PutUpdateVacationUsageResp,
  GetVacationUsagesByPeriodReq,
  GetVacationUsagesByPeriodResp,
  GetUserVacationUsagesByPeriodReq,
  GetUserVacationUsagesByPeriodResp,
  GetUserMonthlyVacationStatsReq,
  GetUserMonthlyVacationStatsResp,
  GetUserVacationStatsReq,
  GetUserVacationStatsResp,
  PostManualGrantVacationReq,
  PostManualGrantVacationResp,
  DeleteRevokeVacationGrantResp,
  PostRequestVacationReq,
  PostRequestVacationResp,
  PostApproveVacationReq,
  PostApproveVacationResp,
  PostRejectVacationReq,
  PostRejectVacationResp,
  GetAllVacationsByApproverReq,
  GetUserRequestedVacationsReq,
  ApproverInfo,
  GetUserRequestedVacationsResp,
  GetUserRequestedVacationStatsReq,
  GetUserRequestedVacationStatsResp,
  PostCancelVacationRequestReq,
  PostCancelVacationRequestResp,
  GetAllUsersVacationSummaryResp,
} from '@/entities/vacation/model/types'

// API
export { vacationApi } from '@/entities/vacation/api/vacationApi'

// Query keys & hooks
export {
  vacationKeys,
  useUserVacationHistoryQuery,
  useAllUsersVacationHistoryQuery,
  useAllUsersVacationSummaryQuery,
  useAvailableVacationsQuery,
  useVacationUsagesByPeriodQuery,
  useUserVacationUsagesByPeriodQuery,
  useUserMonthlyVacationStatsQuery,
  useUserVacationStatsQuery,
  useAllVacationsByApproverQuery,
  useUserRequestedVacationsQuery,
  useUserRequestedVacationStatsQuery,
  usePostUseVacationMutation,
  usePutUpdateVacationUsageMutation,
  useDeleteVacationUsageMutation,
  usePostManualGrantVacationMutation,
  useDeleteRevokeVacationGrantMutation,
  usePostRequestVacationMutation,
  usePostApproveVacationMutation,
  usePostRejectVacationMutation,
  usePostCancelVacationRequestMutation,
} from '@/entities/vacation/api/vacationQueries'
